def key_positions(seq, key):
    """
    Takes a sequence and a key function
    returns an array such that the ith element
    of the array is the starting position of objects
    in seq whose key is i
    """
    temp_list = []
    for char in seq:
        temp_list.append(key(char))
    k = max(temp_list)

    C = []
    for i in range(0, k+1):
        C.append(0)

    for a in seq:
        C[key(a)] = C[key(a)] + 1
    
    sum = 0
    for i in range(0, k+1):
        C[i], sum = sum, sum + C[i]
    return C

def sorted_array(seq, key, positions):
    """
    Takes a sequence, a key function,
    and an array of key positions generated by
    key_positions
    and produces an array containing the elements
    of seq according to the key function
    """
    B = []
    for i in range(0, len(seq)):
        B.append(0)
    for a in seq:
        B[positions[key(a)]] = a
        positions[key(a)] = positions[key(a)] + 1
    return B